func decToChar(number: Int) -> String? {
        switch number {
        case 161:
            return "ก"
        case 162:
            return "ข"
        case 163:
            return "ฃ"
        case 164:
            return "ค"
        case 165:
            return "ฅ"
        case 166:
            return "ฆ"
        case 167:
            return "ง"
        case 168:
            return "จ"
        case 169:
            return "ฉ"
        case 170:
            return "ช"
        case 171:
            return "ซ"
        case 172:
            return "ฌ"
        case 173:
            return "ญ"
        case 174:
            return "ฎ"
        case 175:
            return "ฏ"
        case 176:
            return "ฐ"
        case 177:
            return "ฑ"
        case 178:
            return "ฒ"
        case 179:
            return "ณ"
        case 180:
            return "ด"
        case 181:
            return "ต"
        case 182:
            return "ถ"
        case 183:
            return "ท"
        case 184:
            return "ธ"
        case 185:
            return "น"
        case 186:
            return "บ"
        case 187:
            return "ป"
        case 188:
            return "ผ"
        case 189:
            return "ฝ"
        case 190:
            return "พ"
        case 191:
            return "ฟ"
        case 192:
            return "ภ"
        case 193:
            return "ม"
        case 194:
            return "ย"
        case 195:
            return "ร"
        case 196:
            return "ฤ"
        case 197:
            return "ล"
        case 198:
            return "ฦ"
        case 199:
            return "ว"
        case 200:
            return "ศ"
        case 201:
            return "ษ"
        case 202:
            return "ส"
        case 203:
            return "ห"
        case 204:
            return "ฬ"
        case 205:
            return "อ"
        case 206:
            return "ฮ"
            
        default: return nil
    
        }
    }
